apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-consensusmonitor
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/preserve-trailing-slash: "true"
spec:
  tls:
  - hosts:
    - "consensusmonitor.{{ .Values.domain }}"
  rules:
  - host: "consensusmonitor.{{ .Values.domain }}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: consensus-monitor
            port:
              number: 8080
